# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'MediaInfoAppSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
use_frameworks!
  pod 'Kingfisher', '~> 3.13.0'
  pod 'ObjectMapper'
  pod 'RealmSwift'

end
